/*
 To change this license header, choose License Headers in Project Properties.
 To change this template file, choose Tools | Templates
 and open the template in the editor.
 */
package vista;

import controlador.Gestor;
import controlador.RDB;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import modelo.Material;

/**

 @author Arlen
 */
public class Consultas extends javax.swing.JInternalFrame
{

    /** Creates new form Consultas */
    public Consultas(Pp p)
    {
        initComponents();
        this.p = p;
        modeloTablaM = (DefaultTableModel)tblMaterial.getModel();
        modeloTablaS = (DefaultTableModel)tblSilla.getModel();
        Gestor.updateMateriales();
    }

    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rbtDesc = new javax.swing.JRadioButton();
        rbtAsc = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscarTodos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSilla = new javax.swing.JTable();
        cmbMaterial1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbEstilo = new javax.swing.JComboBox<>();
        lblPrecio1 = new javax.swing.JLabel();
        barra1 = new javax.swing.JSlider();

        jLabel3.setText("jLabel3");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "cod_Material", "Tipo", "Precio"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMaterial);

        jLabel1.setText("Ordenar todos por:");

        buttonGroup1.add(rbtDesc);
        rbtDesc.setText("Precio descendente");

        buttonGroup1.add(rbtAsc);
        rbtAsc.setText("Precio ascendente");

        jLabel2.setText("Buscar por Tipo:");

        txtTipo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtTipoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarTodos.setText("Buscar");
        btnBuscarTodos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBuscarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(rbtDesc)
                        .addGap(37, 37, 37)
                        .addComponent(rbtAsc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarTodos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtDesc)
                    .addComponent(rbtAsc)
                    .addComponent(btnBuscarTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Material", jPanel2);

        tblSilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "cod_Material", "ID", "Estilo", "Giratoria", "Reclinable", "Precio"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSilla);

        cmbMaterial1.setModel(Gestor.materiales);
        cmbMaterial1.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbMaterial1ItemStateChanged(evt);
            }
        });

        jLabel10.setText("Material");

        jRadioButton1.setText("Todas");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        jLabel4.setText("ESTILO");

        cmbEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderno", "Rustico", "Clásico", "Todos" }));
        cmbEstilo.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbEstiloItemStateChanged(evt);
            }
        });

        lblPrecio1.setText("precio<");

        barra1.setMaximum(1000);
        barra1.setValue(0);
        barra1.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                barra1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbEstilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lblPrecio1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(barra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(barra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Silla", jPanel1);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarActionPerformed
    {//GEN-HEADEREND:event_btnBuscarActionPerformed
     
        createTableMateriales("SELECT * FROM material where tipo like '" + txtTipo.getText() + "' " + getOrder());
        txtTipo.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbMaterial1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbMaterial1ItemStateChanged
    {//GEN-HEADEREND:event_cmbMaterial1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            String style = "";
            if(!cmbEstilo.getModel().getSelectedItem().toString().equalsIgnoreCase("Todos"))
            {
                style = " and estilo like '" + cmbEstilo.getModel().getSelectedItem().toString() + "'";
            }
            createTableSilla("select * from silla where codMaterial="
                             + ((Material)cmbMaterial1.getSelectedItem()).getCod()
                             + style
            );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMaterial1ItemStateChanged

    private void cmbEstiloItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbEstiloItemStateChanged
    {//GEN-HEADEREND:event_cmbEstiloItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            String style = "";
            if(!cmbEstilo.getModel().getSelectedItem().toString().equalsIgnoreCase("Todos"))
            {
                style = " and estilo like '" + cmbEstilo.getModel().getSelectedItem().toString() + "'";
            }
            createTableSilla("select * from silla where codMaterial="
                             + ((Material)cmbMaterial1.getSelectedItem()).getCod()
                             + style
            );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstiloItemStateChanged

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jRadioButton1ItemStateChanged
    {//GEN-HEADEREND:event_jRadioButton1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        {
            createTableSilla("select * from silla");
        }
        else
        {
            modeloTablaS.setRowCount(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtTipoActionPerformed
    {//GEN-HEADEREND:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnBuscarTodosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBuscarTodosActionPerformed
    {//GEN-HEADEREND:event_btnBuscarTodosActionPerformed
    
        createTableMateriales("SELECT * FROM material " + getOrder());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarTodosActionPerformed

    private void barra1StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_barra1StateChanged
    {//GEN-HEADEREND:event_barra1StateChanged
      modeloTablaS.setRowCount(0);
         lblPrecio1.setText("precio<"+barra1.getValue());
                createTableSilla("SELECT * FROM silla left join material on material.precio <"+barra1.getValue()+ getOrder());





// TODO add your handling code here:
    }//GEN-LAST:event_barra1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barra1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarTodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbEstilo;
    private javax.swing.JComboBox<modelo.Material> cmbMaterial1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JRadioButton rbtAsc;
    private javax.swing.JRadioButton rbtDesc;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTable tblSilla;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
Pp p;
    DefaultTableModel modeloTablaM;
    DefaultTableModel modeloTablaS;
    public void createTableMateriales(String sql)
    {
        modeloTablaM.setRowCount(0);
        try
        {
            int i = 0;
            ResultSet rs = RDB.query(Gestor.connect(1),sql);
            while(rs.next())
            {
                modeloTablaM.setRowCount(modeloTablaM.getRowCount() + 1);
                modeloTablaM.setValueAt(rs.getInt("codMaterial"),i,0);
                modeloTablaM.setValueAt(rs.getString("tipo"),i,1);
                modeloTablaM.setValueAt(rs.getFloat("precio"),i,2);
                i++;
            }
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }
    public void createTableSilla(String sql)
    {
        modeloTablaS.setRowCount(0);
        try
        {
            int i = 0;
            ResultSet rs = RDB.query(Gestor.connect(1),sql);
            while(rs.next())
            {
                Material m = Gestor.getMaterial(rs.getInt("codMaterial"));
                
                modeloTablaS.setRowCount(modeloTablaS.getRowCount() + 1);
                modeloTablaS.setValueAt(m.getCod(),i,0);
                modeloTablaS.setValueAt(rs.getInt("id"),i,1);
                modeloTablaS.setValueAt(rs.getString("estilo"),i,2);
                if(rs.getInt("giratoria")==1){
                  modeloTablaS.setValueAt("Si",i,3);  
                }else{
                     modeloTablaS.setValueAt("No",i,3);  
                }
                if(rs.getInt("reclinable")==1){
                   modeloTablaS.setValueAt("SI",i,4);  
                }else{
                     modeloTablaS.setValueAt("NO",i,4);
                }
               
                modeloTablaS.setValueAt(m.getPrecio(),i,5);
                i++;
            }
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }
public String getOrder(){
      String order = "";
                if(rbtAsc.isSelected())
                {
                    order = " order by precio asc";
                }
                else
                {
                    order = " order by precio desc";
                }
                return order;
}
}
