/*
 To change this license header, choose License Headers in Project Properties.
 To change this template file, choose Tools | Templates
 and open the template in the editor.
 */
package vista;



/**

 @author Arlen
 */
public class Pp extends javax.swing.JFrame
{

    /** Creates new form Pp */
    public Pp()
    {
        initComponents();
        this.setTitle("Mueblería Arlen");
     this.setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnMaterial = new javax.swing.JMenu();
        jmnProduct = new javax.swing.JMenu();
        mniSilla = new javax.swing.JMenuItem();
        jmnConsultar = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jmnMaterial.setText("Material");
        jmnMaterial.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jmnMaterialMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmnMaterial);

        jmnProduct.setText("Productos");

        mniSilla.setText("Silla");
        mniSilla.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mniSillaActionPerformed(evt);
            }
        });
        jmnProduct.add(mniSilla);

        jMenuBar1.add(jmnProduct);

        jmnConsultar.setText("Consultar");
        jmnConsultar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jmnConsultarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmnConsultar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnMaterialMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jmnMaterialMouseClicked
    {//GEN-HEADEREND:event_jmnMaterialMouseClicked
        if(evt.getClickCount() == 1)
        {
            MaterialF m = new MaterialF(this);
            m.setVisible(true);
                 jDesktopPane1.add(m);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnMaterialMouseClicked

    private void jmnConsultarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jmnConsultarMouseClicked
    {//GEN-HEADEREND:event_jmnConsultarMouseClicked
        Consultas consult=new Consultas(this);
        consult.setVisible(true);
        jDesktopPane1.add(consult);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnConsultarMouseClicked

    private void mniSillaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniSillaActionPerformed
    {//GEN-HEADEREND:event_mniSillaActionPerformed
        Seat s = new Seat(this);
        s.setVisible(true);
        jDesktopPane1.add(s);

        // TODO add your handling code here:
    }//GEN-LAST:event_mniSillaActionPerformed

    /**
     @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Pp.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Pp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jmnConsultar;
    private javax.swing.JMenu jmnMaterial;
    private javax.swing.JMenu jmnProduct;
    private javax.swing.JMenuItem mniSilla;
    // End of variables declaration//GEN-END:variables
}
